// <auto-generated />
using System;
using EFCoreDbContextPoolingSample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDbContextPoolingSample.Migrations
{
    [DbContext(typeof(CatDbContext))]
    [Migration("20240911121706_SeedingMoreCatsDb")]
    partial class SeedingMoreCatsDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreDbContextPoolingSample.Entities.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Breed")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6eb2104-506a-45e9-9f71-5d2a5df4357a"),
                            Age = 12,
                            Breed = 1,
                            Nickname = "Miau"
                        },
                        new
                        {
                            Id = new Guid("d284d8c0-6fa0-401c-b239-48d736d1d584"),
                            Age = 2,
                            Breed = 1,
                            Nickname = "Garfield"
                        },
                        new
                        {
                            Id = new Guid("d3d5ea45-068b-4293-a962-1f1ad6a7a5fa"),
                            Age = 5,
                            Breed = 4,
                            Nickname = "Bilu"
                        },
                        new
                        {
                            Id = new Guid("f5166711-047a-40ba-b95d-33cd31965f65"),
                            Age = 1,
                            Breed = 2,
                            Nickname = "Nanan"
                        },
                        new
                        {
                            Id = new Guid("6719e0e3-77cf-4328-831f-61af0e623a49"),
                            Age = 7,
                            Breed = 3,
                            Nickname = "Ghraarrr"
                        },
                        new
                        {
                            Id = new Guid("ba5c26a2-bf46-4443-9902-346e98fbcc9f"),
                            Age = 4,
                            Breed = 0,
                            Nickname = "Poof"
                        },
                        new
                        {
                            Id = new Guid("33427e77-4ccc-4907-a81c-1522a4dffa28"),
                            Age = 8,
                            Breed = 4,
                            Nickname = "Chorão"
                        },
                        new
                        {
                            Id = new Guid("58045a1f-6a49-4514-ac0e-5dc67b4e2b17"),
                            Age = 9,
                            Breed = 3,
                            Nickname = "Briguento"
                        },
                        new
                        {
                            Id = new Guid("4143777a-0ad5-404a-8af2-a6224fe2a3c2"),
                            Age = 6,
                            Breed = 3,
                            Nickname = "Miau Safado"
                        },
                        new
                        {
                            Id = new Guid("3af5723b-eb68-4039-b455-e537b8f9ded5"),
                            Age = 1,
                            Breed = 3,
                            Nickname = "Desconhecido"
                        },
                        new
                        {
                            Id = new Guid("f86f7c36-e7bd-4b41-b397-8c60a64d0e86"),
                            Age = 4,
                            Breed = 4,
                            Nickname = "Desconhecido"
                        },
                        new
                        {
                            Id = new Guid("4ba47fd1-a2b7-4abb-9e97-d3ec979918c4"),
                            Age = 1,
                            Breed = 0,
                            Nickname = "Desconhecido"
                        },
                        new
                        {
                            Id = new Guid("8b1fd40e-2472-43db-9082-2a27e0b043df"),
                            Age = 1,
                            Breed = 4,
                            Nickname = "Desconhecido"
                        },
                        new
                        {
                            Id = new Guid("72f24f81-c90e-4e45-837e-58609f79d20d"),
                            Age = 4,
                            Breed = 2,
                            Nickname = "Desconhecido"
                        },
                        new
                        {
                            Id = new Guid("26a0264b-3db1-4dbf-abe9-4e91b311f523"),
                            Age = 6,
                            Breed = 1,
                            Nickname = "Desconhecido"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
