// <auto-generated />
using System;
using EFCoreDbContextPoolingSample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDbContextPoolingSample.Migrations
{
    [DbContext(typeof(CatDbContext))]
    [Migration("20240910222532_InitialAndSeedingDb")]
    partial class InitialAndSeedingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreDbContextPoolingSample.Entities.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Breed")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58a9b59d-b886-418c-a219-b71f1771218e"),
                            Age = 12,
                            Breed = 1,
                            Nickname = "Miau"
                        },
                        new
                        {
                            Id = new Guid("a21e78f4-4d14-4c1a-bbe7-42c85bbfd6b0"),
                            Age = 12,
                            Breed = 1,
                            Nickname = "Garfield"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
